wait for run-scripts daemon message in background

diff --git a/jsession b/jsession
--- a/jsession
+++ b/jsession
@@ -81,17 +81,20 @@ else
     export DBUS_SESSION_BUS_ADDRESS
 fi
 # run startup scripts
-reply="`dbus-send --system --type=method_call --print-reply \
-        --dest=prog.jsession /prog/jsession prog.jsession.cmd \
-        int16:$startup_code &> /dev/null`"
-if [ $? -ne 0 ]; then
-    if [ "${reply##*: }" = "couldn't run command" ]; then
-        echo "warning: daemon couldn't run root startup scripts" 1>&2
-    else
-        echo "warning: couldn't run root startup scripts (is daemon" \
-             "running?)" 1>&2
+{
+    reply="`dbus-send --system --type=method_call --print-reply \
+            --dest=prog.jsession /prog/jsession prog.jsession.cmd \
+            int16:$startup_code &> /dev/null`"
+    if [ $? -ne 0 ]; then
+        if [ "${reply##*: }" = "couldn't run command" ]; then
+            echo "warning: daemon couldn't run root startup scripts" 1>&2
+        else
+            echo "warning: couldn't run root startup scripts (is daemon" \
+                 "running?)" 1>&2
+        fi
     fi
-fi
+} &
+
 # change to conf's directory so it can use relative paths
 cd "$(dirname "$conf")"
 # source login shell initialisation file
