jsession cleanup, source ~/.profile on login

diff --git a/jsession b/jsession
--- a/jsession
+++ b/jsession
@@ -6,13 +6,6 @@
 # included, you can find it here:
 #     http://www.gnu.org/licenses/gpl-3.0.txt
 
-# shell="$(grep "^$LOGNAME:" /etc/passwd)"
-# shell="${shell##*/}"
-# zsh: ~/.zprofile
-# csh, tcsh: ~/.login
-# else: ~/.profile
-# https://en.wikipedia.org/wiki/Template:Unix_shells
-
 startup_code=4
 
 conf=$1
@@ -29,8 +22,9 @@ conf is a configuration file (Bash source file) defining init and noinit as
 Duplicate lines will be executed as many times as they appear, even across
 multiple 'init' files.
 
-On login, all executable files in /etc/jsession/startup are executed as root by
-the jsession daemon, if running (using run-parts).
+On login, the file ~/.profile is sourced, and all executable files in
+/etc/jsession/startup are executed as root by the jsession daemon, if running
+(using run-parts).
 
     jsession -h
     jsession --help
@@ -43,8 +37,8 @@ default_conf=/etc/jsession/conf
 if [ -z "$conf" ] || ! source "$conf" 2> /dev/null; then
     [ -n "$conf" ] &&
         echo "warning: config file doesn't exist; using defaults" 1>&2
-    conf=$default_conf
-    source $default_conf 2> /dev/null || {
+    conf="$default_conf"
+    source "$conf" 2> /dev/null || {
         echo "error: can't find default config file" 1>&2
         exit 1
     }
@@ -58,82 +52,110 @@ disp=`echo $DISPLAY | cut -d"." -f1`
 
 # create config dir if needed
 home=~/.jsession
-mkdir -p $home
+mkdir -p "$home"
 # clean up running jsessions list
-> $home/running-temp
-cat $home/running | while read line; do
+> "$home/running-temp"
+cat "$home/running" | while read line; do
     pid=`echo $line | cut -d" " -f1`
     # copy to new file if still running
-    [ "`ps -p $pid -o comm=`" = jsession ] && echo $line >> $home/running-temp
+    [ "$(ps -p "$pid" -o comm=)" = jsession ] &&
+        echo $line >> "$home/running-temp"
 done
-rm $home/running
-mv $home/running-temp $home/running
+rm "$home/running"
+mv "$home/running-temp" "$home/running"
 # die if jsession already running on this display
-running=`grep " $disp$" $home/running` 
+running="$(grep " $disp$" "$home/running")"
 if [ -n "$running" ]; then
     echo "error: jsession is already running on this display" 1>&2
     exit 3
 fi
 
-# start dbus
+# start session bus
 if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
     eval `dbus-launch --exit-with-session --sh-syntax`
 else
     export DBUS_SESSION_BUS_ADDRESS
 fi
 # run startup scripts
-if ! dbus-send --system --type=method_call --print-reply --dest=prog.jsession \
-               /prog/jsession prog.jsession.cmd int16:$startup_code &> \
-               /dev/null; then
-    echo "warning: couldn't run root startup scripts (is daemon running?)" 1>&2
+reply="`dbus-send --system --type=method_call --print-reply \
+        --dest=prog.jsession /prog/jsession prog.jsession.cmd \
+        int16:$startup_code &> /dev/null`"
+if [ $? -ne 0 ]; then
+    if [ "${reply##*: }" = "couldn't run command" ]; then
+        echo "warning: daemon couldn't run root startup scripts" 1>&2
+    else
+        echo "warning: couldn't run root startup scripts (is daemon" \
+             "running?)" 1>&2
+    fi
 fi
 # change to conf's directory so it can use relative paths
-cd `dirname $conf`
+cd "$(dirname "$conf")"
+# source login shell initialisation file
+# TODO: is there a way to get the login shell to source it, then inherit its
+#       environment?
+# shell="$(grep "^$LOGNAME:" /etc/passwd)"
+# shell="${shell##*/}"
+# if [ "$shell" = zsh ]; then
+#     source ~/.zprofile
+# elif [ "$shell" = csh ] || [ "$shell" = tcsh ]; then
+#     source ~/.login
+# else # bash, sh, ksh, dash
+#     echo .profile
+#     source ~/.profile
+# fi
+source ~/.profile
+
 # read lists of stuff to run into temporary files
 copy_files () {
     if [ -z "$1" ]; then
         # no files: create destination and return
-        > $2
+        > "$2"
         return
     fi
-    files=$1:
+    files="$1:"
     while [ -n "$files" ]; do
         # get next file
-        src=`echo $files | cut -d: -f1`
-        files=`echo $files | cut -d: -f2-`
+        src="`echo $files | cut -d: -f1`"
+        files="`echo $files | cut -d: -f2-`"
         # copy
-        cat $src >> $2 2> /dev/null
+        cat "$src" >> "$2" 2> /dev/null
         # add newline if none at end of file
-        [ `tail -c1 $2` ] && echo >> $2
+        nl="`echo`"
+        [ "$(tail -c1 "$2")" != "$nl" ] && echo >> $2
     done
 }
-dest=/tmp/jsession-$$
-copy_files "$init" $dest-init
-init=$dest-init
-copy_files "$noinit" $dest-noinit
-noinit=$dest-noinit
+dest="/tmp/jsession-$$"
+copy_files "$init" "$dest-init"
+init="$dest-init"
+copy_files "$noinit" "$dest-noinit"
+noinit="$dest-noinit"
 # run stuff
 cd ~
-cat $init | while read cmd; do
+cat "$init" | while read cmd; do
     # skip if a comment or blank
-    [ "`echo $cmd | head -c1`" == "#" ] || [ -z "$cmd" ] && continue
+    [ -z "$cmd" ] || [ "${cmd:0:1}" = "#" ] && continue
     # check if in $noinit
-    cat $noinit | while read notcmd; do
-        [ "$cmd" == "$notcmd" ] && continue
+    skip=n
+    cat "$noinit" | while read notcmd; do
+        if [ "$cmd" = "$notcmd" ]; then
+            skip=y
+            break
+        fi
     done
+    [ "$skip" = y ] && continue
     # check if command (first word) is on the path
-    if [ `type -P \`echo $cmd | cut -d" " -f1\`` ]; then
-        # run it
-        ($cmd &) || echo "warning: failed to run command: $cmd" 1>&2
+    if type -P "$(echo "$cmd" | cut -d" " -f1)" &> /dev/null; then
+        # run it (can't check if it died because it's backgrounded)
+        $cmd &
     else
         echo "warning: command not found: $cmd" 1>&2
     fi
 done
 # cleanup
-rm $init $noinit
+rm "$init" "$noinit"
 
 # write PID/display to file
-echo $$ $disp >> $home/running
+echo $$ $disp >> "$home/running"
 
 # set up trap
 do_logout () {
@@ -144,8 +166,8 @@ do_logout () {
 trap do_logout TERM INT
 
 # keep a child running so we can use wait and handle signals without a delay
-while :; do
-    if [ ! $cpid ] || [ ! `ps -p $cpid -o pid=` ]; then
+while true; do
+    if [ -z "$cpid" ] || ! ps -p $cpid &> /dev/null ; then
         # child not running
         sleep 3600 &
         cpid=$!
