root startup scripts support

diff --git a/jsession b/jsession
--- a/jsession
+++ b/jsession
@@ -68,6 +68,11 @@ if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
 else
     export DBUS_SESSION_BUS_ADDRESS
 fi
+# run startup scripts
+if ! dbus-send --system --type=method_call --print-reply --dest=prog.jsession \
+               /prog/jsession prog.jsession.cmd int16:$code &> /dev/null; then
+    echo "error: couldn't run root startup scripts (is daemon running?)" 1>&2
+    exit 4
 # change to conf's directory so it can use relative paths
 cd `dirname $conf`
 # read lists of stuff to run into temporary files
